### ISSUE TITLE
Synchronization between PCs

### ISSUE THREAD

**Issue by flaiker** [fidley/ABAPFavorites#11]
Hi Łukasz, thanks for the plugin!

One question: I am currently struggling keeping my eclipse settings in sync between three PCs (especially dark theme settings btw...). Is there a file I could check into a private repo with git to synchronize the favorites?

**Comment by fidley** [comment]
Hi, 
Thanks! To sync your favorites you have to go to your workspace and search for favorites.xml file in the plugins folder. The folder containing it should start from com.abapblog.... Can't remember exactly now. But I'll check later and give you a hint. 

Cheers 
Łukasz

**Comment by flaiker** [comment]
Got it, it's `$WORKSPACE/.metadata/.plugins/com.abapblog.favorites/favorites.xml`.

**Comment by fidley** [comment]
I've just added a new issue #12 to add function to export / import the favorites. Hope to do it soon.
