### ISSUE TITLE
Drag and Drop development objects between Favorite Folders

### ISSUE THREAD

**Issue by Sdfraga** [fidley/ABAPFavorites#19]
Change the development object root folder by drag and drop

**Comment by fidley** [comment]
Will try to implement this soon, sorry it takes so long, but I had only small amount of time that I could spend on this, so I didn't even started.

I found this links that will help me to include DnD into TreeView.

https://www.eclipse.org/articles/Article-Workbench-DND/drag_drop.html, http://www.java2s.com/Code/Java/SWT-JFace-Eclipse/SWTDNDDragandDropcomprehensiveExample.htm

**Comment by fidley** [comment]
http://www.java2s.com/Code/Java/SWT-JFace-Eclipse/DragandDropexamplesnippetdragleafitemsinatree.htm one more link
