### ISSUE TITLE
Add text files to folders

### ISSUE THREAD

**Issue by Sdfraga** [fidley/ABAPFavorites#20]
It would be nice if we could add text files to folders.
I am using the folders to manage my different projects using ADT and I would like to add text files with some notes regarding the correspondent project.

**Comment by fidley** [comment]
@Sdfraga  what do you think about adding instead a possibility to store long description, which will be visible after right click and selecting some new action from context menu. For example "Display object Long Text". There You could put some notes, but this would be still integrated into favorites XML file?

**Comment by Sdfraga** [comment]
Hello @fidley,

If I could add this lond descriptions on the folders it will be ok.
As I told you I use the folders to manage different projects on the client, so it would be nice to add my notes on the folders instead of using a separate tool for that.

Let me know if I could assist you in anything.

**Comment by fidley** [comment]
Long description added to the edit window.
