### ISSUE TITLE
Add possibility to add objects to favorites from context menu

### ISSUE THREAD

**Issue by fidley** [fidley/ABAPFavorites#28]

**Comment by fidley** [comment]
@BlueTeck This seems to be more complex than expected, or my knowledge of Java & Eclipse is too small :)  I've asked Thomas Fiedler for the newest SDK in order to be able to complete that...

**Comment by MDagni** [comment]
Aah to bad, I've been eagerly waiting for this :)

**Comment by fidley** [comment]
@MDagni as former ABAP Developer the developments in Java are for me quite hard, or maybe not in Java but in Eclipse environment. I think I'm still not understanding fully the extensions and extensions points  and that could be a problem :P

**Comment by fidley** [comment]
@MDagni @BlueTeck Ok, so I've started with this and it seems possible. Simply I was doing lot's of errors in past tries. I have now the object type and name, the next step will be to create a simple TreeViewer to select the destination of the adding an object. I will keep you informed about next steps

**Comment by BlueTeck** [comment]
@fidley thanks for your effort

**Comment by MDagni** [comment]
Have you finished it yet? Because I can see it works 😃

**Comment by fidley** [comment]
Almost... as always on productive eclipse it works a bit different, with some bugs :) I'm trying to correct them :)

**Comment by fidley** [comment]
@MDagni does the window stays open for you as well after adding the object to favorites?

**Comment by MDagni** [comment]
Yes, that's the glitch I'm talking about.

**Comment by fidley** [comment]
@MDagni  Should be now ok. There are two ways to add favorites -> context menu of project explorer and context menu of editor :) This second option should be also now visible after upgrade to 1.0.37

**Comment by MDagni** [comment]
Ah, I loved that one in the editor's context menu! It's easier to add now. Wonderful!
Thank you so much for all your efforts. I don't know how many people use this, but I believe every ADT user should have this ❤️

**Comment by fidley** [comment]
Thanks :) Let's see if I haven't forgotten any type of object :) Have fun

**Comment by BlueTeck** [comment]
Thanks a lot!
