### ISSUE TITLE
Good day i cant install  abap 

### ISSUE THREAD

**Issue by netmoleCZ** [fidley/ABAPFavorites#30]
Cannot complete the install because one or more required items could not be found.
  Software being installed: ABAP Favorites 1.0.26 (ABAP_Favorites_Feature_Project.feature.group 1.0.26)
  Missing requirement: Favorites 1.0.26 (com.abapblog.favorites 1.0.26) requires 'osgi.bundle; org.eclipse.emf.ecore 2.15.0' but it could not be found
  Cannot satisfy dependency:
    From: ABAP Favorites 1.0.26 (ABAP_Favorites_Feature_Project.feature.group 1.0.26)
    To: org.eclipse.equinox.p2.iu; com.abapblog.favorites [1.0.26,1.0.26]

can anybody suggest me resolution i am on eclipse photon

**Comment by fidley** [comment]
Hi @netmoleCZ , 
please try to install 1.0.27 version. I've removed the dependency to org.eclipse.emf.ecore. Seems SAP has corrected their plugin which was forcing me to use this dependency.
#31 
Cheers
Łukasz

**Comment by netmoleCZ** [comment]
fixed
