### ISSUE TITLE
Opening RFC function module opens RFC service instead

### ISSUE THREAD

**Issue by MDagni** [fidley/ABAPFavorites#32]
Hi Fidley.
I've just found this plugin by recommendation of Florian Henninger on SCN, and I absolutely love it! It's way better than the Bookmarks view of Eclipse.
I have a few problems though, so I'll open an issue for each of them.

First one: I added an RFC function module which also has an RFC service to favorites. When I double click in Favorites, it opens the RFC service instead of the function module. Can you check that please?

To reproduce the issue, go to table TADIR with OBJECT = SRFC and pick any OBJ_NAME. Add it to a development objects folder in Favorites, then try to open it by double clicking.

![image](https://user-images.githubusercontent.com/33897441/50312050-269fa100-04b8-11e9-8bdd-fadca4e57a92.png)

**Comment by fidley** [comment]
thanks for kind words. I'll check what I can do with it.

**Comment by MDagni** [comment]
This is also fixed. Thank you very much 😃
