### ISSUE TITLE
Project dependent folders collapse when changing active project

### ISSUE THREAD

**Issue by MDagni** [fidley/ABAPFavorites#33]
I have created two development objects folder - Folder 1 project independent, Folder 2 dependent on project ARQ, 
When the active system is ARQ I expand both folders. 
![image](https://user-images.githubusercontent.com/33897441/50312571-d1648f00-04b9-11e9-8fb4-ac64cefc39e4.png)

When I switch to project AED, Folder 2 disappears, which is fine.
![image](https://user-images.githubusercontent.com/33897441/50312594-e4775f00-04b9-11e9-85db-d1ac156ebee5.png)

When I switch back to project ARQ, Folder 2 appears but it's collapsed. I have to expand it again.
![image](https://user-images.githubusercontent.com/33897441/50312607-ef31f400-04b9-11e9-970f-492380e6d2af.png)

Can you fix that please?

**Comment by fidley** [comment]
I'll take a look on that.

**Comment by fidley** [comment]
done with 1.0,42
