### ISSUE TITLE
Make project dependent folders always visible

### ISSUE THREAD

**Issue by MDagni** [fidley/ABAPFavorites#34]
Hi Lukasz.
Project dependent folders are automatically hidden when another project is activated. Is it possible to not hide them, and objects under them should open in the associated project and not the active project?
Thanks.

**Comment by fidley** [comment]
Hi @MDagni , 

that's nice option I will see how I can implement this. Maybe as a configuration option?

Cheers
Łukasz

**Comment by MDagni** [comment]
An option in the folder properties would be nice, just like "Project Independent?".

**Comment by MDagni** [comment]
I love how this works now. I can double click a favorite in another project and it opens up. Perfect!
