### ISSUE TITLE
Ability to open in a specific project

### ISSUE THREAD

**Issue by MDagni** [fidley/ABAPFavorites#35]
Hi Lukasz.
Is it possible for you to add an "Open in project > ..." or "Run in project > ..." option on the context menu of project independent objects? That way it would be easier to open or run an object without first switching to the desired project.
If there are no windows open for that project, I have to open something first, then use the Favorites view in current situation.

By the way, I'm making these suggestions about projects because I have 4 systems I'm working on and they mostly have the same objects. My life would be a lot easier if these suggestions become real.

Thanks.

**Comment by fidley** [comment]
Hello @MDagni ,

Opein in project is already there since few versions. Use right click in the favorites list.

![image](https://user-images.githubusercontent.com/7912195/50337121-7316cb00-0510-11e9-9992-30fef1b9f038.png)

Cheers
Łukasz

**Comment by MDagni** [comment]
I have version 1.0.27 but I can't see that option. I have installed using the update site http://abapblog.com/eclipse/plugin/ABAPFavorites/

![image](https://user-images.githubusercontent.com/33897441/50339969-0f999700-052a-11e9-9dcc-0498843a0e48.png)

**Comment by MDagni** [comment]
Also the "Logon To All SAP Systems" menu doesn't do anything. May be it has a problem with detecting open projects?

Check: Yes it has. When it's looking for open projects, it checks until the first closed project, and ignores the rest. In the screenshot you can see ACQ_300 project is closed, so Favorites only displays the first project.

![image](https://user-images.githubusercontent.com/33897441/50341656-baad4f00-0530-11e9-9fe7-7942153756f3.png)

**Comment by fidley** [comment]
hmm that's strange. I see all projects from my installation, doesn't matter if you're logged in or not. Which version of eclipse do you have and which version of ADT?

**Comment by MDagni** [comment]
It's not about being logged in. If you right click on a project and choose "Close Project", that project will be out of sight until you reopen it. You won't see it in Open ABAP Development Object > Browse dialog for example.
I have Eclipse Photon 4.8.0 and ABAP Core Development Tools 2.102.4

**Comment by fidley** [comment]
ahh, ok. Thanks for clarifying. I will check that soon.

**Comment by MDagni** [comment]
I renamed my projects and deleted unnecessary ones without any fear, all thanks to ABAPFavorites! 👍 😄 

![image](https://user-images.githubusercontent.com/33897441/50342913-1201ee00-0536-11e9-96a4-d597f93466c0.png)

**Comment by fidley** [comment]
@MDagni please try version 1.0.28

**Comment by MDagni** [comment]
That worked great! I closed the first project and one in the middle, it shows the remaining open ones correctly. Thanks 👍
