### ISSUE TITLE
Escaped / to %2F character if Object is added via Context Menu in Editor

### ISSUE THREAD

**Issue by stockbal** [fidley/ABAPFavorites#50]
Let's say I have a namespaced class open in eclipse e.g. `/cwm/cl_md_material`. When I try to add this class to the Favorites/Favorites Dev Objects via the context menu entry "Add To Favorites" of the editor, the name is converted to `%2FCWM%2FCL_MD_MATERIAL`. If I create the Favorite with this name the saved favorite will not open. 

If I add the same object via the context menu entry in the project explorer tree this issue does not occur

**Comment by fidley** [comment]
Found it. When I'm in editor I'm resolving the name of the object from the path in workspace. In case of objects with namespaces the '/' was replaced with %2F as you wrote.

**Comment by fidley** [comment]
@stockbal please install latest version. This will solve the issue.
