### ISSUE TITLE
which version of Eclipse shall be used with your plugin.

### ISSUE THREAD

**Issue by netmoleCZ** [fidley/ABAPFavorites#55]
good day ,

today i was tryed install your plugin to eclipse 2018-8 and i was unable thanks to missing  dependencies can i ask you  which version of eclipse you use  for abap programming.

**Comment by fidley** [comment]
I use now 2019-03 but it is working from Neon up to latest version. The dependency can be only ADT plugin or EMF I think, what exactly your installation error says?

**Comment by netmoleCZ** [comment]
![image](https://user-images.githubusercontent.com/7267433/56791336-1ea99200-6807-11e9-9a89-7df0bc977456.png)

it wont let me install it

**Comment by netmoleCZ** [comment]
![image](https://user-images.githubusercontent.com/7267433/56791430-57496b80-6807-11e9-81de-c9c352a24b9b.png)

do you know why i cant install it on eclipse  2019-3?

**Comment by netmoleCZ** [comment]
![image](https://user-images.githubusercontent.com/7267433/56791518-88c23700-6807-11e9-96f1-53cc9c2bf368.png)

waits for futher instructions how i can instal it ty

**Comment by fidley** [comment]
please try now. Seems I have to put full version name into the Eclipse Marketplace configuration

**Comment by fidley** [comment]
but remember to restart eclipse before trying again

**Comment by fidley** [comment]
If marketplace installation doesn't work you can use this link http://abapblog.com/eclipse/plugin/ABAPFavorites/ and install it manually from Help Menu

![image](https://user-images.githubusercontent.com/7912195/56880707-15fec900-6a5e-11e9-8474-3d458108c31d.png)

**Comment by netmoleCZ** [comment]
ty  for answer fixed
