### ISSUE TITLE
Double click and select the Project

### ISSUE THREAD

**Issue by Sdfraga** [fidley/ABAPFavorites#59]
Hello @fidley ,

In my "Favorites" View I have a list of the most common tcode I use. I was wondering how could I tell the system which project should it use when I select one of the tcodes.
I found #35 that is great and solves my issue. Amazing :)

Nevertheless I was wondering that maybe it could be nice that the project selection appears when I press the tcode in a popup for example. then I could even have a box where I start typing my project ID to filter my list. 
I'm thinking in the system behaviour when I open a new ABAP project and the list of systems configured in the SAP Gui comes up...

Maybe you could use a combination of keys (Double click + ctr for example ) since currently, when I double click a tcode in my Favorites it will open it in the current open project.

This is very low priority but it could be interesting for those who have a lot of projects configured in the ADT.

I am not even sure if it's possible or not but decided to share this thought!

What do you think?

**Comment by fidley** [comment]
Hi @Sdfraga , 
thanks for this idea. I like it, especially the way with ctrl+click. This sounds quite ok. Could be also an option to make it configurable which behaviour you have on double-click, and which on double-click + ctrl.

The popup itself should not be hard to do. I will think about it in the free time.

Thanks for the idea!

**Comment by fidley** [comment]
Released to Update Site! Thanks @stockbal
