### ISSUE TITLE
Copy to Clipboard

### ISSUE THREAD

**Issue by g-back** [fidley/ABAPFavorites#61]
Hi @fidley ,
first of all - thanks for this plugin!

Sometimes I would like to copy the name of an object (Class, Function, Program) from the favorites to the clipboard.

I added this small functionality in my [forked project](https://github.com/g-back/ABAPFavorites/tree/contextmenu-clipboard). 

If you're interested I could add a PR - otherwise you can just close this issue.

**Comment by fidley** [comment]
Hi @g-back, 
I'm always interested for contribution. Sometimes the small changes makes big difference for the users. Please create PR.

Thanks!

**Comment by fidley** [comment]
It's live now ;)

![image](https://user-images.githubusercontent.com/7912195/62130968-7a8a2800-b2da-11e9-9dcc-4389c28a59e7.png)

do you have a twitter handle ?
