### ISSUE TITLE
Quick fix for instant translation

### ISSUE THREAD

**Issue by MDagni** [fidley/ABAPFavorites#64]
Hi Lukasz.

I have an idea for a new Quick fix option: Instant translation using Google Translate.

You know in the standard SAP programs, many of the comments are in German. For people who don't speak German, a translation option which appears after selecting the text and pressing Ctrl+1 would be wonderful. You can use Google Translate API for this purpose.

After I select the text and choose Translate from quick fixes, the resulting text could appear in a popup, just like what you get with pressing F2. If it's not possible, the internal browser of Eclipse can be used.

Also the target language could be an option. I am Turkish but I mostly prefer translation to English (as Google handles it better than Turkish), so in the preferences there can be an option to choose the target languages I want. Then these languages can appear as separate quick fix options, e.g. Translate to English, Translate to Turkish.

Do you think this is feasible?

**Comment by fidley** [comment]
Hi Mehmet,

Good idea. I'll check if this is possible, but probably yes 😁

I'll check after my holidays.

Cheers
Łukasz

W dniu pon., 5.08.2019 o 22:12 Mehmet Dağnilak <notifications@github.com>
napisał(a):

**Comment by fidley** [comment]
Google API needs an API Key which is valid only for certain number of calls. The other option is to use Cloud version of API but also this rather is paid. The same is for Microsoft API, but in this case there are 2 Millions of chars monthly for free. This could be a starting point and there could be a possibility to use own API key to get own limit.  https://docs.microsoft.com/en-us/azure/cognitive-services/translator/quickstart-translate?pivots=programming-language-java should be the starting point in here.

**Comment by fidley** [comment]
done but the issue should be in https://github.com/fidley/ABAPQuickFix

**Comment by MDagni** [comment]
Thanks Lukasz, it works well :) Although it may require some improvement. It would be nice if it removes the * and " marks before translating. Also the quick fix dialog delays a bit because it translates before displaying I guess..

**Comment by fidley** [comment]
Yeah there is always place for improvement. So far the translation is done before displaying the possibility to translate, but only in case in your selection you have a comment. I will check if this is possible to switch the behavior. 

BTW why do you want to get rid of " and * before translating? These are the marks that allows me to put back the comment in correct place.

**Comment by MDagni** [comment]
If the comment contains multiple lines, they appear in the text and break the meaning. For example in this screen (include FV45EF0E_EINTEILUNG_VOR_DATUM_ ):

![image](https://user-images.githubusercontent.com/33897441/65966403-b4a5b080-e468-11e9-92f1-1ab0690ce227.png)

*       Bei Änderung des Gültig-ab-Datums wird geprueft, ob es        *
*       Einteilungen gibt, die vor dem Gülig-ab-Datum liegen          *

If you could remove the *'s and combine the text into one line:

Bei Änderung des Gültig-ab-Datums wird geprueft, ob es Einteilungen gibt, die vor dem Gülig-ab-Datum liegen

It makes a meaningful sentence.

**Comment by fidley** [comment]
![image](https://user-images.githubusercontent.com/7912195/66158767-d77dc380-e626-11e9-8709-904983c151c6.png)

Should be now ok for you with this Preferences settings ON

**Comment by fidley** [comment]
Please close the issue if this solves your problem :)

**Comment by MDagni** [comment]
Looks wonderful! Thank you very much. You're a good man :)
