### ISSUE TITLE
New Setting for enabling/disabling eclipse Navigation

### ISSUE THREAD

**Issue by stockbal** [fidley/ABAPFavorites#66]
Hi @fidley,

Sometimes it would be nice to always stay inside the opened Transaction (e.g. SE80). As it is now, any time I try to open an Object from SE80 it will opened in a new editor in eclipse (e.g. Class, Interface, ...).

Could you please offer a preference setting for this? It could be named like "_Navigate to eclipse for supported development object_" - the same way SAP does it in the dialog to open a new integrated SAP GUI Editor.

The Implementation part should be a simple matter. Just take the preference setting and pass the boolean value to the `enableEclipseNavigation` parameter of the method `openEditorForObject`
```js
public IEditorPart openEditorForObject(IProject project, 
        com.sap.adt.tools.core.model.adtcore.IAdtObjectReference navigationTarget, 
        boolean enableEclipseNavigation,
        String wbOperation
        Map<String, String> setGetParameters, 
        Map<String, String> parameters)
```
https://github.com/fidley/ABAPFavorites/blob/86db006c1a8541b215f8420b795d451bc715bf30/ABAP%20Favorites/src/com/abapblog/favorites/superview/Actions.java#L624

All the best
Ludwig

**Comment by fidley** [comment]
Hello @stockbal ,
I will try to adapt as you wish, I had similar idea, but without SDK it's kind hard to figure out what is possible :)

Cheers

**Comment by fidley** [comment]
Hi @stockbal ,
this should make you happy ;)
![image](https://user-images.githubusercontent.com/7912195/66137569-97561b00-e5fd-11e9-9138-cd87f5fc2014.png)

Cheers
Łukasz

**Comment by stockbal** [comment]
Hi @fidley,

thank you very much :). I just tried it. Works like a charm

Best Regards
Ludwig

**Comment by fidley** [comment]
Have fun ;)
