### ISSUE TITLE
Sort by description

### ISSUE THREAD

**Issue by MDagni** [fidley/ABAPFavorites#77]
Hi @fidley .

It's been a long time since we requested something 🙂  Today's wish is: Would it be possible to sort the objects by description column? The folder structure should remain the same, but objects should be able to be sorted by their description. Right now I have many folders and many objects underneath them with incoherent names; it has become an issue to find the object I need.

Thanks 🙂

**Comment by fidley** [comment]
Hi @MDagni , 
yes, long time no issues here ;) 
It should not be a big problem. I will take a look on it and I'll keep you updated.

Cheers
Łukasz

**Comment by fidley** [comment]
I have it done, just need to check before publishing that everything is fine.

I've added the possibility to change sorting from extended menu. 
![2020-06-05_11h12_09](https://user-images.githubusercontent.com/7912195/83858914-7a8a5e00-a71d-11ea-85d9-37c0efb34b3b.png)

![2020-06-05_11h12_29](https://user-images.githubusercontent.com/7912195/83858918-7c542180-a71d-11ea-9c2d-04ef0010f983.png)

**Comment by fidley** [comment]
released

**Comment by MDagni** [comment]
Works excellent! Thank you very much 🙂 
It doesn't sort Turkish characters very well, but it's not a problem. They appear at the end of the list as in ANSI codepage.

**Comment by fidley** [comment]
> Works excellent! Thank you very much 🙂
> It doesn't sort Turkish characters very well, but it's not a problem. They appear at the end of the list as in ANSI codepage.
You're welcome, well the special characters are always special :) I guess it will be the same for all languages... maybe something to check later :)
