### ISSUE TITLE
Error when upgrading from 1.0.51 to 1.0.60 or installing straight to 1.0.60

### ISSUE THREAD

**Issue by pixelbaker** [fidley/ABAPFavorites#79]
Hi there. I having an installation/upgrade problem with the ABAP Favorites plugin. 

I am using a fresh installation of Eclipse 2020-06 and ADT Core Development Tools 3.12.1.
When I install your plugin from the Update Site "http://abapblog.com/eclipse/plugin/ABAPFavorites" then I get the following error:
![image](https://user-images.githubusercontent.com/29891579/91022545-a7039700-e5f5-11ea-8ba8-002ecb1c9f9b.png)

I then installed the "latest" 1.0.51 version, which worked.
When I then try to upgrade via "Check for Updates" I get the same error as above.

Interestingly the marketplace also just offers me 1.0.51.
![image](https://user-images.githubusercontent.com/29891579/91023102-68baa780-e5f6-11ea-9007-53e50bf7e377.png)

When I try to mirror your plugin via Eclipse cli tool, it seems not to download the other dependencies of your plugin.
```
C:\Windows\system32>"D:\Programme\Eclipse_201909\eclipse\eclipsec.exe" -nosplash -verbose -application org.eclipse.equinox.p2.artifact.repository.mirrorApplication -source http://abapblog.com/eclipse/plugin/ABAPFavorites -destination D:\test\14
Mirroring: org.eclipse.update.feature,com.abapblog.adt.extension.feature,1.0.0.5 (Descriptor: canonical: org.eclipse.update.feature,com.abapblog.adt.extension.feature,1.0.0.5)
```

Any ideas what could cause that problem?

Thanks a lot for the hard work, and the cool Plugin.

**Comment by fidley** [comment]
Tnx for pointing the error, I need to check but it seems strange. Normally there should be only ADT and Eclipse UI dependencies inside, from which the Eclipse one you should always have in your installation, and the ADT one should not be the issue as well. 

![image](https://user-images.githubusercontent.com/7912195/91025180-50985780-e5f9-11ea-8536-540c2037d0b6.png)

The marketplace version description is static text, I've just updated it. At the end it points exactly to the same update site.

I'll try to reproduce the issue on my PCs.

**Comment by pixelbaker** [comment]
Thx for looking into it.

**Comment by fidley** [comment]
I just went through the whole installation process:
1. Download and install Eclipse for Java Developers 2020-06
2. Creation of new workspace for fresh installation
3. Installation of ADT tools and restart
4. Installation of ABAP Favorites from Eclipse marketplace

I had no issues at all. The version installed is the latest one, although marketplace still says 1.0.51

![image](https://user-images.githubusercontent.com/7912195/91056961-e4cce380-e626-11ea-98a3-de60eec87ef8.png)

Which version of Eclipse were you installing?

**Comment by pixelbaker** [comment]
I feared so 😉 

Could you do me a favour please and paste in here the log you get from running the following command:
(After adapting the cmd to your environment.)

`"D:\Programme\Eclipse_202003\eclipse\eclipsec.exe" -nosplash -verbose -application org.eclipse.equinox.p2.artifact.repository.mirrorApplication -source http://abapblog.com/eclipse/plugin/ABAPFavorites -destination D:\test\14`

**Comment by pixelbaker** [comment]
And to answer your question: I am using the exact same Eclipse version like you do.

> Eclipse IDE for Java Developers (includes Incubating components)
> 
> Version: 2020-06 (4.16.0)
> Build id: 20200615-1200

**Comment by fidley** [comment]
When I use the command you've posted, then It stops in the same place.
![image](https://user-images.githubusercontent.com/7912195/91143368-b4328b80-e6b2-11ea-8c45-054d650dec29.png)

**Comment by pixelbaker** [comment]
I am actually glad that you have the same output. 
So, the problem is not on your end at all. I need to dig deeper it seems.
Thank you very much for the time you invested.

ABAP Favorites (+ Dev Objects) is a huge helper in my workflow and I am spreading the word inside the team I am working.

All the best!

**Comment by fidley** [comment]
You're welcome and thanks for the kind words!
