### ISSUE TITLE
Copy & paste folders

### ISSUE THREAD

**Issue by fidley** [fidley/ABAPFavorites#80]
Hello Lukasz,
Your plugin is extremely useful !!! Have you considered adding a feature to the Favorites view to copy an existing folder (including all child folders and objects) and paste it into another folder? I would like to see it work no matter how the existing and target folders are defined (Independent or DevObject).
Thanks, Roland

comming from https://marketplace.eclipse.org/comment/7175#comment-7175

**Comment by mraht** [comment]
I'd like to be able to change/set the parent folder directly in the edit screen of a folder - would be really useful, e.g. for organizing customer- or task-related development objects.

**Comment by aztechowski** [comment]
I've tried to reorganise my favorites and it's extremly unconvinient without aforementionen funktionality.

**Comment by fidley** [comment]
I've corrected the drag & drop and I've added the possibility to copy the nodes instead of moving (using CTRL key while dropping).

![1 0 64 move and copy with drag and drop](https://github.com/fidley/ABAPFavorites/assets/7912195/5d60e20e-3e84-4023-83dc-54bc99ebfb4b)
Additionally you use "Move to folder" function on each element.
![1 0 64 move to folder](https://github.com/fidley/ABAPFavorites/assets/7912195/12e98220-6d95-4639-b031-4757f6f4c8c7)
Or "Move folder to root" on subfolders.
![1 0 64 move folder to root](https://github.com/fidley/ABAPFavorites/assets/7912195/4660b3fb-0c94-4c5a-ab47-39d9f7f9be67)

**Comment by mraht** [comment]
This looks really nice - many thanks!
