### ISSUE TITLE
Add Long Description to column and add Searching in Long Descriptions

### ISSUE THREAD

**Issue by hitek1878** [fidley/ABAPFavorites#88]
1. Can we add long description to column? so i can open folder and see 20 objects and i can see what was purpose of that object ( example transaction via long description ) ? any mass quick display functionality other than new column would be nice also 
2. Can we than in search allow searching in long descriptions ? I can put than some tags in long descriptions and search by tags or sth like that.  So tool will receive some additional flexibility 

thx BR Rafal

**Comment by fidley** [comment]
Hi @hitek1878, 
I was sure that search also checks the long text, but now I'm not sure :) 

I'll check if I can do it in short time and I'll update you here.

Cheers
Łukasz

**Comment by fidley** [comment]
Will be added with next release. Still working on final view look

![image](https://github.com/fidley/ABAPFavorites/assets/7912195/465d8475-9138-4c02-a17d-3f237685d964)

**Comment by fidley** [comment]
Deployed to update site.
