### ISSUE TITLE
Expand option in ABAP Favourites 

### ISSUE THREAD

**Issue by tomasz-grabarczyk** [fidley/ABAPFavorites#91]
Hello Łukasz,
First of all, thank you for all the work you do, it helps greatly in day to day life in Eclipse.
I wonder, if it would be possible to add the expand buttons to ABAP Favourites, so it would be possible to expand every folder the same way it works in Vertical Tabs (which is also beautiful piece of work)?
Thank you!

**Comment by fidley** [comment]
Cześć Tomasz, 
sure I can add such buttons. Although in some cases it may be not easy to read all elements.
I will add this in next release.

Cheers
Łukasz

**Comment by fidley** [comment]
You can update plugin in few minutes to get the button on toolbar.
