### ISSUE TITLE
favorites invisible after login to abap project

### ISSUE THREAD

**Issue by FD1899** [fidley/ABAPFavorites#93]
Hi,

after updating to the latest version 1.0.60 my favorites aren't shown after log in to my project. 
When I click on "sort by..." everythings is fine. Can you have a look at this? 

Kind regards,
Frank

**Comment by fidley** [comment]
Hi Frank, 
can you please go to Help->About Eclipse IDE then click on the AbapBlog.com icon
![image](https://github.com/fidley/ABAPFavorites/assets/7912195/c2240218-7685-4459-bcb6-df0ceffc11ce)
And paste the exact version you have?
![image](https://github.com/fidley/ABAPFavorites/assets/7912195/5e2ea6e2-00f4-4e2a-b228-99e1e62574ff)

The info from Eclipse marketplace is not always up to date.
Can you share also the info about your eclipse installation and java version?

**Comment by fidley** [comment]
Maybe you have also something in Error Log view?

**Comment by FD1899** [comment]
Hi Lukasz,

here is the exact version of the plugin:
![image](https://github.com/fidley/ABAPFavorites/assets/166493004/1cb809dc-40cf-4b32-ba5d-a074a9b43482)

ans here for eclipse:
![image](https://github.com/fidley/ABAPFavorites/assets/166493004/c2ab400d-2196-460d-abd9-a01e4d18d33b)

I'm not sure where I can find the java version, can you show me?

The error logs has no entries corresponding to the plugin.

Regards!

**Comment by fidley** [comment]
![image](https://github.com/fidley/ABAPFavorites/assets/7912195/76f63379-b04b-4088-900c-4e173b256b99)
Then swith to Configuration tab and scroll some until you'll find Java info
![image](https://github.com/fidley/ABAPFavorites/assets/7912195/1a06d3b5-f47d-4ff0-a123-322c64591fc2)

**Comment by fidley** [comment]
I'll try to reproduce on my machine with same version if I'll be able

**Comment by aztechowski** [comment]
I've the same issue with Favorites Dev Objtects. What helps is to close and open the widget again

**Comment by fidley** [comment]
Thanks, now I have a point where I could catch the error :)

**Comment by FD1899** [comment]
Hi Lukasz,
now it work's perfect. Thank you!
Kind regards,
Frank

**Comment by aztechowski** [comment]
> please try the installation of the version 1.0.64 available from now.

Work like a charm. Thank you!
