### ISSUE TITLE
[NEW] Open includes

### ISSUE THREAD

**Issue by mraht** [fidley/ABAPFavorites#98]
Currently if I favorite an include I can't open it afterwards from the favorites list. It'd be nice if include could be opened the same as classes or reports itself.

**Comment by fidley** [comment]
Thanks for this, I'll try to implement in next days

**Comment by fidley** [comment]
In few minutes the version with the correction of this bug should appear.
Sorry for delay

**Comment by mraht** [comment]
Many thanks - includes can be opened now :)
